// <auto-generated />
namespace Inspinia_MVC5_SeedProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class DatosDeTareasEnCantidadEnTablaUsuarios : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DatosDeTareasEnCantidadEnTablaUsuarios));
        
        string IMigrationMetadata.Id
        {
            get { return "202003252047251_DatosDeTareasEnCantidadEnTablaUsuarios"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
