// <auto-generated />
namespace Inspinia_MVC5_SeedProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class lotlag : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lotlag));
        
        string IMigrationMetadata.Id
        {
            get { return "202003131939351_lotlag"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
